"""changing CLick table primary keys

Revision ID: ed53dc076d2e
Revises: f8b922afcad5
Create Date: 2025-05-20 18:01:01.872112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed53dc076d2e'
down_revision: Union[str, None] = 'f8b922afcad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'id')
    op.create_primary_key('pk_clicks', 'clicks', ['ip_address', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('pk_clicks', 'clicks', type_='primary')
    # ### end Alembic commands ###
